### ISSUE TITLE
No such attribute foaf:name on a CSS pod

### ISSUE THREAD

**Issue by bourgeoa** [solidcryptpad/solidcryptpad#4]
I tried a CSS pod https://solidweb.me, it seems to work, but I got this non blocking error.

![image](https://user-images.githubusercontent.com/2218470/201486749-6c9f08ad-70d6-474c-a97c-95ad2bb76318.png)

**Comment by Otto-AA** [comment]
Fixed in https://github.com/solidcryptpad/solidcryptpad/commit/74f93fee06fcb93b454f6004863647ef11e9c24f

We previously assumed that all users have a username, but CSS doesn't provide it per default, so it's definitely good to fix that :ok_hand:
